version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
    - yezz123
    commit-message:
      prefix: ⬆
  # Rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
    - yezz123
    commit-message:
      prefix: ⬆